# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.ssh.insert_key = false
  config.vm.network :private_network, ip: "192.168.34.10"
  config.vm.define :centos_server do |server|
    server.vm.box = "centos1706v2"
    server.vm.provider :virtualbox do |vb|
      vb.customize ["modifyvm", :id, "--memory", "2048","--cpus", "8", "--name", "centos_webserver_chef" ]
    end
#    server.vm.provision "shell", inline: <<-SHELL
#      yum install -y httpd
#      yum install -y wget
#      cd /var/www/html
#      wget www.icesi.edu.co
#      systemctl start httpd.service
#      systemctl enable httpd.service
#    SHELL
       config.vm.provision :chef_solo do |chef|
       chef.install = false
       chef.cookbooks_path = "cookbooks"
       chef.add_recipe "httpd"
    end 
  end
end
